# Generated by Django 5.2.4 on 2026-07-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.JSONField(default=dict)),
                ('type', models.CharField(choices=[('Tx', 'Text'), ('Li', 'List')], default='Tx', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('notes', models.ManyToManyField(blank=True, to='notes.notes')),
            ],
        ),
    ]
